### ISSUE TITLE
undefined method 'metadef' 

### ISSUE THREAD

**Issue by geronimod** [hallison/sinatra-mapping#3]
Hi, i'm getting this error when added sinatra-mapping gem:

....rvm/gems/ruby-1.9.2-p290@xxxxx/gems/sinatra-mapping-1.2.0/lib/sinatra/mapping.rb:36:in map': undefined methodmetadef' for Sinatra::Application:Class (NoMethodError)
from ....rvm/gems/ruby-1.9.2-p290@xxxxx/gems/sinatra-1.3.2/lib/sinatra/base.rb:1602:in `block (2 levels) in delegate'

@rkh from sinatra core team suggest me that you must change metadef calls by define_method, i try to change it by myself but i get involved in another issue.

Thanks for your help.

pd: i'm using ruby 1.9.2 p290, my gems stack:

backports (2.3.0) 
eventmachine (0.12.10) 
i18n (0.6.0) 
mime-types (1.17.2) 
polyglot (0.3.3) 
treetop (1.4.10) 
mail (2.4.4) 
pony (1.4) 
rack (1.3.6) 
rack-flash (0.1.2) 
rack-protection (1.2.0) 
rack-test (0.6.1) 
tilt (1.3.3) 
sinatra (1.3.2) 
sinatra-contrib (1.3.2) from git://github.com/sinatra/sinatra-contrib.git (at master) 
sinatra-mapping (1.2.0) 
bundler (1.0.22)

**Comment by hallison** [comment]
Hi @geronimod ,

This error occurred because the main method which creates extension methods was removed since Sinatra v1.x. Try include in your Gemfile the version 1.0.0:

```
gem "sinatra", "~>1.0"
```

**Comment by geronimod** [comment]
Hi @hallison, thanks for the advice but i can't downgrade Sinatra for others dependencies, you got planned replace the "metadef" references to fix the issue for Sinatra > 1.0 ?

Best regards.

**Comment by hallison** [comment]
@geronimod I'll fix this error. Please, wait for news.

Thanks for your contribution.

**Comment by hallison** [comment]
@geronimod Other user solved this problem. I will release a new gem. Thanks.
